version: '3.8'

services:
  # Servicio de base de datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mi_aplicacion
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password123
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  # Servicio PHP-FPM
  php:
    build: ./php
    container_name: php_container
    restart: always
    volumes:
      - ./php:/var/www/html
    networks:
      - app_network
    depends_on:
      - db

  # Servicio Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - php

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge